export type TrafficSourceType = "legacy" | "external" | "search" | "internal";
export type DetectedIntent = "explore" | "understand" | "compare" | "act";
export type DestinationLayer = "dcc" | "wts" | "parr" | "checkout";
export type NextStepStatus = "full" | "partial" | "none";
export type CanonicalStatus = "canonical" | "redirects-to-canonical";

export type IntentRegistryEntry = {
  sourcePath: string;
  sourceType: TrafficSourceType;
  detectedIntent: DetectedIntent;
  intentFamily: string | null;
  destinationPath: string;
  destinationAnchor: string | null;
  destinationType: DestinationLayer;
  canonicalStatus: CanonicalStatus;
  intentMatchScore: 1 | 2 | 3 | 4 | 5;
  nextStepClarity: 1 | 2 | 3 | 4 | 5;
  needsIntentUpgrade: boolean;
  needsRewrite: boolean;
  needsRedirect: boolean;
  needsDedicatedLandingPage: boolean;
  nextStepExists: NextStepStatus;
  primaryNextStep: string | null;
  secondaryNextSteps: string[];
  notes: string;
};

export const INTENT_REGISTRY: IntentRegistryEntry[] = [
  {
    sourcePath: "/downtown",
    sourceType: "external",
    detectedIntent: "act",
    intentFamily: "pickup-logistics",
    destinationPath: "/guide/local/denver-pickups",
    destinationAnchor: "downtown-pickup",
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 5,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "High-intent downtown pickup traffic now lands on the exact Denver pickup confirmation block with immediate shuttle and private booking CTAs.",
  },
  {
    sourcePath: "/upper-north",
    sourceType: "legacy",
    detectedIntent: "act",
    intentFamily: "parking-arrival",
    destinationPath: "/guide/local/denver-pickups",
    destinationAnchor: "private-pickup",
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/private",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Upper North transport traffic now lands on the booking-choice section where private ride is the first obvious move.",
  },
  {
    sourcePath: "/la-quinta-fairfield",
    sourceType: "legacy",
    detectedIntent: "act",
    intentFamily: "pickup-logistics",
    destinationPath: "/guide/local/denver-pickups",
    destinationAnchor: "hotel-pickup",
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Hotel-area pickup traffic now lands on the Sheraton pickup section with direct movement into shuttle or private booking.",
  },
  {
    sourcePath: "/mishawaka",
    sourceType: "external",
    detectedIntent: "understand",
    intentFamily: "venue-transport",
    destinationPath: "/venues/mishawaka-amphitheatre",
    destinationAnchor: "private-transportation",
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book-all-venue?venue=mishawaka-amphitheatre",
    secondaryNextSteps: [],
    notes: "Legacy Mishawaka social traffic now lands on the transport-options section with the direct booking request visible immediately.",
  },
  {
    sourcePath: "/mishawaka-private-transportation",
    sourceType: "legacy",
    detectedIntent: "act",
    intentFamily: "private-transport",
    destinationPath: "/venues/mishawaka-amphitheatre",
    destinationAnchor: "private-transportation",
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book-all-venue?venue=mishawaka-amphitheatre",
    secondaryNextSteps: [],
    notes: "Private Mishawaka traffic now lands on the transport-options section with the booking request CTA in view.",
  },
  {
    sourcePath: "/post/*pickup*",
    sourceType: "legacy",
    detectedIntent: "act",
    intentFamily: "pickup-logistics",
    destinationPath: "/guide/local/denver-pickups",
    destinationAnchor: "downtown-pickup",
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 5,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Legacy pickup posts now resolve into the downtown pickup launch section instead of the generic guide hub.",
  },
  {
    sourcePath: "/post/*parking*",
    sourceType: "legacy",
    detectedIntent: "understand",
    intentFamily: "parking-arrival",
    destinationPath: "/guide/parking",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 3,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "partial",
    primaryNextStep: "/red-rocks/transportation",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Legacy parking posts now land on the parking guide, but the page can still route harder into transport booking.",
  },
  {
    sourcePath: "/post/*tailgate*",
    sourceType: "legacy",
    detectedIntent: "understand",
    intentFamily: "tailgating-pre-show",
    destinationPath: "/guide/tailgating",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 3,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "partial",
    primaryNextStep: "/guide/show-night-strategy",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Legacy tailgating posts land on the right pre-show surface, but the forward route into transport planning is still only moderate.",
  },
  {
    sourcePath: "/post/*weather*",
    sourceType: "legacy",
    detectedIntent: "understand",
    intentFamily: "weather-what-to-bring",
    destinationPath: "/guide/show-night-strategy",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 3,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "partial",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/red-rocks/transportation"],
    notes: "Weather and clothing legacy posts now reach show-night planning directly, but the action step is still secondary.",
  },
  {
    sourcePath: "/post/*post-show*",
    sourceType: "legacy",
    detectedIntent: "understand",
    intentFamily: "post-show-departure",
    destinationPath: "/guide/show-night-strategy/post-show-pickup-plan",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 5,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Post-show legacy traffic now lands on the exact post-show pickup plan page with direct ride-booking exits.",
  },
  {
    sourcePath: "/post/*shuttle-vs-uber*",
    sourceType: "legacy",
    detectedIntent: "compare",
    intentFamily: "compare-decision",
    destinationPath: "/red-rocks/transportation/shuttle-vs-uber",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 5,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Legacy compare-intent posts now land on the correct decision surface with direct booking exits.",
  },
  {
    sourcePath: "/post/*",
    sourceType: "legacy",
    detectedIntent: "understand",
    intentFamily: "legacy-blog-catchall",
    destinationPath: "/guide",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 3,
    nextStepClarity: 2,
    needsIntentUpgrade: true,
    needsRewrite: true,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "partial",
    primaryNextStep: "/red-rocks/transportation",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Only the uncategorized legacy post traffic still falls back to the guide hub. This is now the remaining weak Wix catchall.",
  },
  {
    sourcePath: "/party-bus-to-red-rocks",
    sourceType: "legacy",
    detectedIntent: "act",
    intentFamily: "private-transport",
    destinationPath: "/party-bus",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/private",
    secondaryNextSteps: [],
    notes: "Good action alignment as long as the party bus page keeps the booking path obvious.",
  },
  {
    sourcePath: "/red-rocks/transportation",
    sourceType: "search",
    detectedIntent: "understand",
    intentFamily: "transport-overview",
    destinationPath: "/red-rocks/transportation",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared", "/book/red-rocks-amphitheatre/private"],
    notes: "Core transport authority page. This is the right canonical surface for broad Red Rocks transportation intent.",
  },
  {
    sourcePath: "/guide/local/denver-pickups",
    sourceType: "search",
    detectedIntent: "act",
    intentFamily: "pickup-logistics",
    destinationPath: "/guide/local/denver-pickups",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Denver pickup page now behaves like a booking launchpad with pickup confirmation and immediate shuttle/private CTAs.",
  },
  {
    sourcePath: "/shuttles",
    sourceType: "search",
    detectedIntent: "compare",
    intentFamily: "compare-decision",
    destinationPath: "/shuttles",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Good mid-funnel compare surface for shuttle seekers.",
  },
  {
    sourcePath: "/book/red-rocks-amphitheatre",
    sourceType: "search",
    detectedIntent: "act",
    intentFamily: "booking-selector",
    destinationPath: "/book/red-rocks-amphitheatre",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 5,
    nextStepClarity: 5,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Primary booking selector for Red Rocks transport traffic.",
  },
  {
    sourcePath: "/book/red-rocks-amphitheatre/custom/shared",
    sourceType: "search",
    detectedIntent: "act",
    intentFamily: "shared-booking",
    destinationPath: "/book/red-rocks-amphitheatre/custom/shared",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 5,
    nextStepClarity: 5,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "checkout",
    secondaryNextSteps: [],
    notes: "Canonical shared shuttle action page.",
  },
  {
    sourcePath: "/book/red-rocks-amphitheatre/private",
    sourceType: "search",
    detectedIntent: "act",
    intentFamily: "private-booking",
    destinationPath: "/book/red-rocks-amphitheatre/private",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 5,
    nextStepClarity: 5,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "checkout",
    secondaryNextSteps: [],
    notes: "Canonical private ride action page.",
  },
  {
    sourcePath: "/guide/sheraton-pickup",
    sourceType: "legacy",
    detectedIntent: "act",
    intentFamily: "pickup-logistics",
    destinationPath: "/guide/local/denver-pickups",
    destinationAnchor: "downtown-pickup",
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 5,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Legacy Sheraton pickup alias now lands on the exact downtown pickup section with immediate booking paths.",
  },
  {
    sourcePath: "/guide/post-encore-strategy",
    sourceType: "legacy",
    detectedIntent: "understand",
    intentFamily: "post-show-departure",
    destinationPath: "/guide/show-night-strategy/post-show-pickup-plan",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Good logistics intent match after redirect.",
  },
  {
    sourcePath: "/guide/bag-policy-2026",
    sourceType: "legacy",
    detectedIntent: "understand",
    intentFamily: "bag-policy",
    destinationPath: "/guide/logistics/bag-policy",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 3,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "partial",
    primaryNextStep: "/guide/show-night-strategy",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Rules traffic is informational, but should still route into show-night planning.",
  },
  {
    sourcePath: "/sprinter",
    sourceType: "legacy",
    detectedIntent: "act",
    intentFamily: "private-transport",
    destinationPath: "/private-van",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/private",
    secondaryNextSteps: [],
    notes: "Vehicle-specific action traffic resolves well into the private ride flow.",
  },
  {
    sourcePath: "/concert-guide",
    sourceType: "legacy",
    detectedIntent: "understand",
    intentFamily: "concert-planning",
    destinationPath: "/red-rocks/concert-guide",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "redirects-to-canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/week/red-rocks"],
    notes: "Legacy concert guide alias routes into a strong authority page.",
  },
  {
    sourcePath: "/red-rocks",
    sourceType: "search",
    detectedIntent: "understand",
    intentFamily: "venue-overview",
    destinationPath: "/red-rocks",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/week/red-rocks", "/red-rocks/transportation"],
    notes: "Primary Red Rocks authority entry surface.",
  },
  {
    sourcePath: "/schedule",
    sourceType: "search",
    detectedIntent: "compare",
    intentFamily: "compare-decision",
    destinationPath: "/schedule",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 4,
    nextStepClarity: 4,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/week/red-rocks",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre"],
    notes: "Schedule traffic is compare-oriented and should keep event-to-booking links strong.",
  },
  {
    sourcePath: "/week/red-rocks",
    sourceType: "search",
    detectedIntent: "compare",
    intentFamily: "compare-decision",
    destinationPath: "/week/red-rocks",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 5,
    nextStepClarity: 5,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Strong comparison surface with direct booking movement.",
  },
  {
    sourcePath: "/handoff/dcc",
    sourceType: "internal",
    detectedIntent: "act",
    intentFamily: "partner-handoff",
    destinationPath: "/handoff/dcc",
    destinationAnchor: null,
    destinationType: "parr",
    canonicalStatus: "canonical",
    intentMatchScore: 5,
    nextStepClarity: 5,
    needsIntentUpgrade: false,
    needsRewrite: false,
    needsRedirect: false,
    needsDedicatedLandingPage: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared", "/book/red-rocks-amphitheatre/private"],
    notes: "Partner intake endpoint that resolves DCC transport intent into the correct live Party at Red Rocks flow.",
  },
];
