export type TrafficSourceType = "legacy" | "external" | "search" | "internal";
export type DetectedIntent = "explore" | "understand" | "compare" | "act";
export type DestinationLayer = "dcc" | "wts" | "parr" | "checkout";
export type NextStepStatus = "full" | "partial" | "none";

export type IntentRegistryEntry = {
  sourcePath: string;
  sourceType: TrafficSourceType;
  detectedIntent: DetectedIntent;
  destinationPath: string;
  destinationType: DestinationLayer;
  intentMatchScore: 1 | 2 | 3 | 4 | 5;
  needsIntentUpgrade: boolean;
  nextStepExists: NextStepStatus;
  primaryNextStep: string | null;
  secondaryNextSteps: string[];
  notes: string;
};

export const INTENT_REGISTRY: IntentRegistryEntry[] = [
  {
    sourcePath: "/downtown",
    sourceType: "external",
    detectedIntent: "act",
    destinationPath: "/guide/local/denver-pickups",
    destinationType: "parr",
    intentMatchScore: 3,
    needsIntentUpgrade: true,
    nextStepExists: "partial",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "High-intent pickup traffic. Landing page should confirm Denver pickup locations fast and push directly into shuttle booking.",
  },
  {
    sourcePath: "/upper-north",
    sourceType: "legacy",
    detectedIntent: "act",
    destinationPath: "/guide/local/denver-pickups",
    destinationType: "parr",
    intentMatchScore: 3,
    needsIntentUpgrade: true,
    nextStepExists: "partial",
    primaryNextStep: "/book/red-rocks-amphitheatre/private",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Parking-adjacent transport traffic should land on a page that makes booking the next move obvious.",
  },
  {
    sourcePath: "/la-quinta-fairfield",
    sourceType: "legacy",
    detectedIntent: "act",
    destinationPath: "/guide/local/denver-pickups",
    destinationType: "parr",
    intentMatchScore: 3,
    needsIntentUpgrade: true,
    nextStepExists: "partial",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: [],
    notes: "Hotel pickup traffic is action-oriented and should resolve to booking faster.",
  },
  {
    sourcePath: "/mishawaka",
    sourceType: "external",
    detectedIntent: "understand",
    destinationPath: "/venues/mishawaka-amphitheatre",
    destinationType: "parr",
    intentMatchScore: 3,
    needsIntentUpgrade: true,
    nextStepExists: "partial",
    primaryNextStep: "/book-all-venue?venue=mishawaka-amphitheatre",
    secondaryNextSteps: [],
    notes: "Legacy social traffic needs immediate transport framing, not just venue editorial context.",
  },
  {
    sourcePath: "/mishawaka-private-transportation",
    sourceType: "legacy",
    detectedIntent: "act",
    destinationPath: "/venues/mishawaka-amphitheatre",
    destinationType: "parr",
    intentMatchScore: 2,
    needsIntentUpgrade: true,
    nextStepExists: "partial",
    primaryNextStep: "/book-all-venue?venue=mishawaka-amphitheatre",
    secondaryNextSteps: [],
    notes: "Private-transport intent is stronger than the current landing promise. Needs a clearer private ride route on-page.",
  },
  {
    sourcePath: "/post/:slug*",
    sourceType: "legacy",
    detectedIntent: "understand",
    destinationPath: "/guide",
    destinationType: "parr",
    intentMatchScore: 2,
    needsIntentUpgrade: true,
    nextStepExists: "partial",
    primaryNextStep: "/red-rocks/transportation",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Wix blog legacy traffic consolidates correctly, but the guide page still needs stronger routing based on transport intent.",
  },
  {
    sourcePath: "/party-bus-to-red-rocks",
    sourceType: "legacy",
    detectedIntent: "act",
    destinationPath: "/party-bus",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/private",
    secondaryNextSteps: [],
    notes: "Good action alignment as long as the party bus page keeps the booking path obvious.",
  },
  {
    sourcePath: "/red-rocks/transportation",
    sourceType: "search",
    detectedIntent: "understand",
    destinationPath: "/red-rocks/transportation",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared", "/book/red-rocks-amphitheatre/private"],
    notes: "Core transport authority page. This is the right canonical surface for broad Red Rocks transportation intent.",
  },
  {
    sourcePath: "/guide/local/denver-pickups",
    sourceType: "search",
    detectedIntent: "act",
    destinationPath: "/guide/local/denver-pickups",
    destinationType: "parr",
    intentMatchScore: 3,
    needsIntentUpgrade: true,
    nextStepExists: "partial",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "High-intent pickup page should read more like a booking launchpad than a static guide.",
  },
  {
    sourcePath: "/shuttles",
    sourceType: "search",
    detectedIntent: "compare",
    destinationPath: "/shuttles",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Good mid-funnel compare surface for shuttle seekers.",
  },
  {
    sourcePath: "/book/red-rocks-amphitheatre",
    sourceType: "search",
    detectedIntent: "act",
    destinationPath: "/book/red-rocks-amphitheatre",
    destinationType: "parr",
    intentMatchScore: 5,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Primary booking selector for Red Rocks transport traffic.",
  },
  {
    sourcePath: "/book/red-rocks-amphitheatre/custom/shared",
    sourceType: "search",
    detectedIntent: "act",
    destinationPath: "/book/red-rocks-amphitheatre/custom/shared",
    destinationType: "parr",
    intentMatchScore: 5,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "checkout",
    secondaryNextSteps: [],
    notes: "Canonical shared shuttle action page.",
  },
  {
    sourcePath: "/book/red-rocks-amphitheatre/private",
    sourceType: "search",
    detectedIntent: "act",
    destinationPath: "/book/red-rocks-amphitheatre/private",
    destinationType: "parr",
    intentMatchScore: 5,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "checkout",
    secondaryNextSteps: [],
    notes: "Canonical private ride action page.",
  },
  {
    sourcePath: "/guide/sheraton-pickup",
    sourceType: "legacy",
    detectedIntent: "act",
    destinationPath: "/guide/local/denver-pickups",
    destinationType: "parr",
    intentMatchScore: 3,
    needsIntentUpgrade: true,
    nextStepExists: "partial",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: [],
    notes: "Legacy pickup alias with high action intent.",
  },
  {
    sourcePath: "/guide/post-encore-strategy",
    sourceType: "legacy",
    detectedIntent: "understand",
    destinationPath: "/guide/show-night-strategy/post-show-pickup-plan",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/custom/shared",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/private"],
    notes: "Good logistics intent match after redirect.",
  },
  {
    sourcePath: "/guide/bag-policy-2026",
    sourceType: "legacy",
    detectedIntent: "understand",
    destinationPath: "/guide/logistics/bag-policy",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "partial",
    primaryNextStep: "/guide/show-night-strategy",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Rules traffic is informational, but should still route into show-night planning.",
  },
  {
    sourcePath: "/sprinter",
    sourceType: "legacy",
    detectedIntent: "act",
    destinationPath: "/private-van",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre/private",
    secondaryNextSteps: [],
    notes: "Vehicle-specific action traffic resolves well into the private ride flow.",
  },
  {
    sourcePath: "/concert-guide",
    sourceType: "legacy",
    detectedIntent: "understand",
    destinationPath: "/red-rocks/concert-guide",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/week/red-rocks"],
    notes: "Legacy concert guide alias routes into a strong authority page.",
  },
  {
    sourcePath: "/red-rocks",
    sourceType: "search",
    detectedIntent: "understand",
    destinationPath: "/red-rocks",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/week/red-rocks", "/red-rocks/transportation"],
    notes: "Primary Red Rocks authority entry surface.",
  },
  {
    sourcePath: "/schedule",
    sourceType: "search",
    detectedIntent: "compare",
    destinationPath: "/schedule",
    destinationType: "parr",
    intentMatchScore: 4,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/week/red-rocks",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre"],
    notes: "Schedule traffic is compare-oriented and should keep event-to-booking links strong.",
  },
  {
    sourcePath: "/week/red-rocks",
    sourceType: "search",
    detectedIntent: "compare",
    destinationPath: "/week/red-rocks",
    destinationType: "parr",
    intentMatchScore: 5,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared"],
    notes: "Strong comparison surface with direct booking movement.",
  },
  {
    sourcePath: "/handoff/dcc",
    sourceType: "internal",
    detectedIntent: "act",
    destinationPath: "/handoff/dcc",
    destinationType: "parr",
    intentMatchScore: 5,
    needsIntentUpgrade: false,
    nextStepExists: "full",
    primaryNextStep: "/book/red-rocks-amphitheatre",
    secondaryNextSteps: ["/book/red-rocks-amphitheatre/custom/shared", "/book/red-rocks-amphitheatre/private"],
    notes: "Partner intake endpoint that resolves DCC transport intent into the correct live Party at Red Rocks flow.",
  },
];
