export type RedRocksShow = {
  isoDate: string;
  formattedDate: string;
  artist: string;
  support: string;
  time: string;
};

// Auto-generated by scripts/build-quick-red-rocks-events.mjs
// Source: data/snapshots/events/redrocks-2026.json
export const upcomingRedRocksShows: RedRocksShow[] = [
  {
    "isoDate": "2026-02-07",
    "formattedDate": "Saturday, February 7, 2026",
    "artist": "Icelantic’s Winter on the Rocks",
    "support": "BigXthaPlug, Smino, Mick Jenkins, PawPaw Rod",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-03-27",
    "formattedDate": "Friday, March 27, 2026",
    "artist": "CRANKDAT",
    "support": "Dr. Fresch, Smoakland, Capochino, HerShe",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-03-28",
    "formattedDate": "Saturday, March 28, 2026",
    "artist": "Ravenscoon & Jantsen",
    "support": "Jason Leech, CHOZEN b2b Noetika, DEV",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-03",
    "formattedDate": "Friday, April 3, 2026",
    "artist": "INZO",
    "support": "What So Not, Lumasi, Daggz, Common Creation, Spenny",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-04",
    "formattedDate": "Saturday, April 4, 2026",
    "artist": "it’s murph presents Murph Rocks",
    "support": "D.O.D, oskar med k, me n ü",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-10",
    "formattedDate": "Friday, April 10, 2026",
    "artist": "ZINGARA & LEVEL UP",
    "support": "Saka, SubDocta, Slang Dogs",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-11",
    "formattedDate": "Saturday, April 11, 2026",
    "artist": "Liquid Stranger",
    "support": "TVBOO b2b AHEE, AVELLO",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-15",
    "formattedDate": "Wednesday, April 15, 2026",
    "artist": "John Mulaney: Mister Whatever",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-16",
    "formattedDate": "Thursday, April 16, 2026",
    "artist": "bbno$",
    "support": "Oliver Tree, Kaarija, YNG Martyr, Jungle Bobby",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-17",
    "formattedDate": "Friday, April 17, 2026",
    "artist": "Sublime",
    "support": "Common Kings, Bumpin Uglies",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-18",
    "formattedDate": "Saturday, April 18, 2026",
    "artist": "Sublime",
    "support": "Pepper, Codefendants",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-19",
    "formattedDate": "Sunday, April 19, 2026",
    "artist": "Wiz Khalifa",
    "support": "2 Chainz, Berner, The Underachievers, Chevy Woods, DJ Bonics",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-20",
    "formattedDate": "Monday, April 20, 2026",
    "artist": "Ice Cube",
    "support": "Big Boi, Czarface",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-21",
    "formattedDate": "Tuesday, April 21, 2026",
    "artist": "Ethel Cain",
    "support": "9Million",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-23",
    "formattedDate": "Thursday, April 23, 2026",
    "artist": "Subtronics – Cyclops Rocks VI (Night 1)",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-24",
    "formattedDate": "Friday, April 24, 2026",
    "artist": "Subtronics – Cyclops Rocks VI (Night 2)",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-26",
    "formattedDate": "Sunday, April 26, 2026",
    "artist": "Bob Moses & Cannons",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-28",
    "formattedDate": "Tuesday, April 28, 2026",
    "artist": "Lewis Capaldi",
    "support": "Joy Crookes",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-29",
    "formattedDate": "Wednesday, April 29, 2026",
    "artist": "Lewis Capaldi",
    "support": "Joy Crookes",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-04-30",
    "formattedDate": "Thursday, April 30, 2026",
    "artist": "Electric Callboy",
    "support": "Polaris, Scene Queen",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-01",
    "formattedDate": "Friday, May 1, 2026",
    "artist": "Two Friends",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-02",
    "formattedDate": "Saturday, May 2, 2026",
    "artist": "Jason Isbell and the 400 Unit",
    "support": "Gillian Welch & David Rawlings",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-03",
    "formattedDate": "Sunday, May 3, 2026",
    "artist": "Puscifer",
    "support": "Dave Hill",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-06",
    "formattedDate": "Wednesday, May 6, 2026",
    "artist": "Bright Eyes – 21 Years of Wide Awake & Digital Ash",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-07",
    "formattedDate": "Thursday, May 7, 2026",
    "artist": "Alejandro Fernández",
    "support": "Camila Fernández",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-09",
    "formattedDate": "Saturday, May 9, 2026",
    "artist": "Cloonee",
    "support": "KETTAMA, Omar+, Cole Knight",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-11",
    "formattedDate": "Monday, May 11, 2026",
    "artist": "YUNGBLUD – IDOLS World Tour",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-13",
    "formattedDate": "Wednesday, May 13, 2026",
    "artist": "Russell Dickerson",
    "support": "Niko Moon",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-16",
    "formattedDate": "Saturday, May 16, 2026",
    "artist": "LIGHTCODE BY LSDREAM / DREAMROCKS II",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-17",
    "formattedDate": "Sunday, May 17, 2026",
    "artist": "THE ELOVATERS",
    "support": "Collie Buddz, The Hip Abduction, Protoje, Donavon Frankenreiter",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-18",
    "formattedDate": "Monday, May 18, 2026",
    "artist": "Khalid",
    "support": "Lauv",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-19",
    "formattedDate": "Tuesday, May 19, 2026",
    "artist": "Kevin Gates",
    "support": "Shoreline Mafia, Ty Dolla $ign",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-21",
    "formattedDate": "Thursday, May 21, 2026",
    "artist": "flipturn",
    "support": "Richy Mitch & The Coal Miners",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-22",
    "formattedDate": "Friday, May 22, 2026",
    "artist": "Seven Lions",
    "support": "Trivecta",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-23",
    "formattedDate": "Saturday, May 23, 2026",
    "artist": "FISHER",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-24",
    "formattedDate": "Sunday, May 24, 2026",
    "artist": "Alabama Shakes",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-25",
    "formattedDate": "Monday, May 25, 2026",
    "artist": "Alabama Shakes",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-29",
    "formattedDate": "Friday, May 29, 2026",
    "artist": "Michael Franti & Spearhead",
    "support": "The Original Wailers",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-05-30",
    "formattedDate": "Saturday, May 30, 2026",
    "artist": "Alan Walker",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-02",
    "formattedDate": "Tuesday, June 2, 2026",
    "artist": "Alex Warren",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-03",
    "formattedDate": "Wednesday, June 3, 2026",
    "artist": "Yo-Yo Ma with Colorado Symphony",
    "support": "Colorado Symphony",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-04",
    "formattedDate": "Thursday, June 4, 2026",
    "artist": "Brit Floyd – The Wall",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-05",
    "formattedDate": "Friday, June 5, 2026",
    "artist": "Brit Floyd – Dark Side of the Moon",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-06",
    "formattedDate": "Saturday, June 6, 2026",
    "artist": "Big Head Todd and the Monsters",
    "support": "4 Non Blondes",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-10",
    "formattedDate": "Wednesday, June 10, 2026",
    "artist": "Lord Huron",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-14",
    "formattedDate": "Sunday, June 14, 2026",
    "artist": "Trevor Hall / Thievery Corporation / Dirtwire",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-15",
    "formattedDate": "Monday, June 15, 2026",
    "artist": "Rod Stewart",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-16",
    "formattedDate": "Tuesday, June 16, 2026",
    "artist": "Rod Stewart",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-17",
    "formattedDate": "Wednesday, June 17, 2026",
    "artist": "Amyl and The Sniffers",
    "support": "L7, PARTY DOZEN",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-18",
    "formattedDate": "Thursday, June 18, 2026",
    "artist": "THIRD DAY – 30th Anniversary",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-19",
    "formattedDate": "Friday, June 19, 2026",
    "artist": "Louis Tomlinson",
    "support": "The Aces",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-20",
    "formattedDate": "Saturday, June 20, 2026",
    "artist": "O.A.R.",
    "support": "Gavin DeGraw, Phantom Planet",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-06-23",
    "formattedDate": "Tuesday, June 23, 2026",
    "artist": "Weird Al Yankovic",
    "support": "Puddles Pity Party",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-07-01",
    "formattedDate": "Wednesday, July 1, 2026",
    "artist": "Treaty Oak Revival",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-07-02",
    "formattedDate": "Thursday, July 2, 2026",
    "artist": "DEADROCKS XII – Zeds Dead",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-07-03",
    "formattedDate": "Friday, July 3, 2026",
    "artist": "DEADROCKS XII – Zeds Dead",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-11-14",
    "formattedDate": "Saturday, November 14, 2026",
    "artist": "mike.",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  },
  {
    "isoDate": "2026-11-15",
    "formattedDate": "Sunday, November 15, 2026",
    "artist": "mike.",
    "support": "Lineup to be announced",
    "time": "7:00 PM"
  }
] as const;
